name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Generate SSH Key
        run: ssh-keygen -t ed25519 -C "GitHub Actions" -f ~/.ssh/id_ed25519 -N ""

      - name: Copy SSH Key to VPS
        run: |
          ssh-copy-id -i ~/.ssh/id_ed25519.pub ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}

      # - name: Deploy to VPS
      #   run: |
      #     ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'